### PR TITLE
Allow setting icons

### PR DESCRIPTION
**Pull request by CristianHenzel**
Screenshot 2020-01-05 at 03 03 32

### CODE REVIEW

**Comment by tcarlsen** [comment]
if theres no icon the new grid will make the name colom 24px wide.

**Comment by CristianHenzel** [comment]
Should be fixed now:

Screenshot 2020-01-07 at 00 54 33

**Comment by tcarlsen** [comment]
sorry again. but I was thinking if no icons on none of the entities. this will leave a 24px "margin" now

**Comment by tcarlsen** [comment]
I think you will need to add a property "hide_icons" and then have 2 deferent grid classes, one with the 24px at the start and another without

```
type: 'custom:light-with-profiles'
title: Lys
hide_icons: true
entities:
```

Further more I think if you should show the entity default icon if none was selected

**Comment by tcarlsen** [comment]
wtf

**Pull request merged**
